package com.birlasoft.testautomation.framework;

public enum Keyword {
	NAVIGATE, WAITTIME, WAITFORELEMENTEXIST, WAITFORELEMENTNOTEXIST, CLICK, CLICKFOCUS, SELECT, MOVETO, MOVEANDCLICK,
	INPUT, KEYBOARDINPUT, SETCHECKBOX, CLEAR, HANDLEALERT, SWITCHWINDOW, SCROLL, SCROLLINTOVIEW, FILEUPLOAD, GETVALUE,
	DATEPICK, ISELEMENTEXIST, ISELEMENTNOTEXIST, ISELEMENTENABLED, VERIFYTEXT, CONTAINSTEXT, VERIFYATTRIBUTE,
	VALIDATELIST, VALIDATETEXTNOTINLIST, RUNPROCESS,LOGINGRS,CREATEPOLICY,VERIFYPOLICYNUMBER,CREATEEVENT,VERIFYEVENTTITLE,
	LOGOUTGRS
}